/-
Copyright (c) 2025 Eric Vergo. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Author: Eric Vergo
-/
import VersoPaper.Basic
import VersoPaper.Blocks
import VersoPaper.Manifest
import VersoPaper.Html

/-!
# VersoPaper

A Verso genre for academic papers with blueprint integration.

This genre allows writing papers in pure Verso markup with hooks to pull
pre-built artifacts from manifest.json, enabling side-by-side display of
formal Lean proofs alongside LaTeX theorem statements.

## Features

- `:::paperStatement "label"` - Insert LaTeX statement with link to Lean code
- `:::paperFull "label"` - Insert full side-by-side display
- `:::paperProof "label"` - Insert just the proof
- `:::leanNode "label"` - Insert a Lean node by label
- `:::leanModule "ModuleName"` - Insert all nodes from a module
- `:::htmlDiv "classes"` - Wrapper div with custom CSS classes
- `:::htmlWrapper "tag"` - Wrapper with custom HTML tag
- `{ref}\`label\`` - Reference link to a blueprint node
- `{lean}\`code\`` - Inline Lean code
- `{span "classes"}\`text\`` - Inline span with CSS classes

## Usage

```lean
import VersoPaper

open Verso.Genre.Paper

-- Define your paper content using Verso markup
-- The manifest.json provides the blueprint data
```

## Architecture

The Paper genre is designed to:
1. Load manifest.json containing pre-computed blueprint data
2. Parse Verso markup with special directives for blueprint content
3. Render HTML/PDF with proper styling and cross-references
4. Support both individual node insertion and bulk module insertion

## Integration with Runway

When used with Runway, the manifest.json is automatically generated by Dress
during the build process. Runway loads the manifest and passes node data to
the Paper genre's HTML renderer via TraverseState.

The rendering is "lazy" in that node lookups happen at HTML render time,
not at elaboration time. This allows the same Verso document to be rendered
with different manifest data (e.g., for different versions of a project).
-/

-- Re-export the main types from Basic
namespace VersoPaper

export Verso.Genre.Paper (
  Paper
  BlockExt
  InlineExt
  PartMetadata
  Config
  TraverseContext
  TraverseState
  TraverseM
  CodeOpts
)

-- Re-export manifest types
export VersoPaper.Manifest (
  Node
  Manifest
  StatusCounts
  CheckResults
  ProjectNotes
)

-- Re-export HTML rendering utilities
export Verso.Genre.Paper (
  renderStatement
  renderProof
  renderFull
  renderMissing
  renderStatusBadge
  paperCss
)

end VersoPaper
